name: Enhanced Screenshot Automation

on:
  pull_request:
    types: [closed]

jobs:
  screenshots:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./AutoSnap

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: ./AutoSnap

      - name: Install Node.js dependencies for Tracewright
        run: |
          cd AutoSnap/tracewrightt
          npm install

      - name: Get PR changes
        id: prdiff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} > changed_files.txt
          cat changed_files.txt

      - name: Detect scenario type (new_feature or ui_change)
        id: detect_mode
        run: |
          if grep -E 'docs/.*\.md' changed_files.txt | xargs grep -iq 'placeholder for a screenshot'; then
            echo "mode=new_feature" >> $GITHUB_OUTPUT
          else
            echo "mode=ui_change" >> $GITHUB_OUTPUT
          fi

      - name: Run enhanced screenshot script
        run: |
          node enhanced-run-script.js --mode ${{ steps.detect_mode.outputs.mode }}
        working-directory: ./AutoSnap 