name: '[PR Gate] Ramsoft Help Manual'
on: 
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: [self-hosted, linux]
    name: '[PR Gate] Ramsoft Help Manual'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build Help Manual
        run: yarn run build